USE [master]
GO
/****** Object:  Database [Test2]    Script Date: 10/6/2021 10:03:35 PM ******/
CREATE DATABASE [Test2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Test2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Test2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Test2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Test2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Test2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Test2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Test2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Test2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Test2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Test2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Test2] SET ARITHABORT OFF 
GO
ALTER DATABASE [Test2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Test2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Test2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Test2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Test2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Test2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Test2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Test2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Test2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Test2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Test2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Test2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Test2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Test2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Test2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Test2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Test2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Test2] SET RECOVERY FULL 
GO
ALTER DATABASE [Test2] SET  MULTI_USER 
GO
ALTER DATABASE [Test2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Test2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Test2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Test2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Test2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Test2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Test2', N'ON'
GO
ALTER DATABASE [Test2] SET QUERY_STORE = OFF
GO
USE [Test2]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10/6/2021 10:03:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Authors]    Script Date: 10/6/2021 10:03:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[AuthorId] [int] IDENTITY(1,1) NOT NULL,
	[AuthorName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED 
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookOrders]    Script Date: 10/6/2021 10:03:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookOrders](
	[OrdersId] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[BookId] [int] NOT NULL,
	[CustomerName] [nvarchar](100) NOT NULL,
	[CustomerAddress] [nvarchar](1000) NOT NULL,
 CONSTRAINT [PK_BookOrders] PRIMARY KEY CLUSTERED 
(
	[OrdersId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 10/6/2021 10:03:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[BookId] [int] IDENTITY(1,1) NOT NULL,
	[BookName] [nvarchar](100) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[BookAuthorId] [int] NOT NULL,
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Books_BookAuthorId]    Script Date: 10/6/2021 10:03:36 PM ******/
CREATE NONCLUSTERED INDEX [IX_Books_BookAuthorId] ON [dbo].[Books]
(
	[BookAuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD  CONSTRAINT [FK_Books_Authors_BookAuthorId] FOREIGN KEY([BookAuthorId])
REFERENCES [dbo].[Authors] ([AuthorId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Books] CHECK CONSTRAINT [FK_Books_Authors_BookAuthorId]
GO
USE [master]
GO
ALTER DATABASE [Test2] SET  READ_WRITE 
GO
